# Generated by Django 4.0.2 on 2023-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='preview',
            field=models.URLField(max_length=255),
        ),
    ]
