# Generated by Django 4.0.2 on 2023-05-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_doc_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='preview',
            field=models.ImageField(default='media/default_images/default_document.png', upload_to='media'),
        ),
    ]
