# Generated by Django 4.2.1 on 2023-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_doc_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=15, unique=True)),
                ('color', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('color', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='studies',
            field=models.ManyToManyField(to='app.study'),
        ),
        migrations.AddField(
            model_name='doc',
            name='subjects',
            field=models.ManyToManyField(to='app.subject'),
        ),
    ]
