# Generated by Django 4.2.1 on 2023-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_like_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
