# Generated by Django 4.2.1 on 2023-06-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_doc_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
