# Generated by Django 4.2.1 on 2023-06-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
